apiVersion: v2
name: observatory-auth-svc
description: Observatory Auth Service — OIDC-based authentication
type: application
version: 0.1.2
appVersion: "1.5.4"
keywords:
  - observatory
  - auth
  - oidc
  - jwt
maintainers:
  - name: luciocarvalhojr
