apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observatory-auth-svc.fullname" . }}
  labels:
    {{- include "observatory-auth-svc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "observatory-auth-svc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "observatory-auth-svc.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: observatory-auth-svc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "observatory-auth-svc.fullname" . }}-config
            - secretRef:
                name: {{ include "observatory-auth-svc.fullname" . }}-secret
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
